# Site settings
title: Meeple Con Dublin
email:
description: > # this means to ignore newlines until "baseurl:"
url: "http://aidan-duggan.github.io/meeplecondublin"
baseurl: "/meeplecondublin"

twitter_username:
github_username:

# Build settings
markdown: kramdown
